// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzquAyMfQmiJSZP4m26q5E0k9P7X97d2I',
    appId: '1:1006763035386:web:0ce6a6181e4f3d95b9d743',
    messagingSenderId: '1006763035386',
    projectId: 'sylvera-a461e',
    authDomain: 'sylvera-a461e.firebaseapp.com',
    storageBucket: 'sylvera-a461e.firebasestorage.app',
    measurementId: 'G-XP4E59CWHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJYUjns9ADj5_WmxCP5vpiRzLLDdN7hY',
    appId: '1:1006763035386:android:1de92ec41a68f0fdb9d743',
    messagingSenderId: '1006763035386',
    projectId: 'sylvera-a461e',
    storageBucket: 'sylvera-a461e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5aA1AVQaWeMR1c0ZJnYbS81ap5ng-8eM',
    appId: '1:1006763035386:ios:efb4a15aab415476b9d743',
    messagingSenderId: '1006763035386',
    projectId: 'sylvera-a461e',
    storageBucket: 'sylvera-a461e.firebasestorage.app',
    iosClientId: '1006763035386-6mriivvdq57vljgj44s2erhdgdhpfir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sylveraFe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5aA1AVQaWeMR1c0ZJnYbS81ap5ng-8eM',
    appId: '1:1006763035386:ios:efb4a15aab415476b9d743',
    messagingSenderId: '1006763035386',
    projectId: 'sylvera-a461e',
    storageBucket: 'sylvera-a461e.firebasestorage.app',
    iosClientId: '1006763035386-6mriivvdq57vljgj44s2erhdgdhpfir5.apps.googleusercontent.com',
    iosBundleId: 'com.example.sylveraFe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzquAyMfQmiJSZP4m26q5E0k9P7X97d2I',
    appId: '1:1006763035386:web:0ef71286922b9991b9d743',
    messagingSenderId: '1006763035386',
    projectId: 'sylvera-a461e',
    authDomain: 'sylvera-a461e.firebaseapp.com',
    storageBucket: 'sylvera-a461e.firebasestorage.app',
    measurementId: 'G-K7XDR0P4HE',
  );
}
